language: python
sudo: false
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install python-coveralls tox tox-travis
script: tox --recreate
after_success:
- pip install -r requirements.txt -e .
- py.test --cov=ddd_base --cov-report=term-missing tests
- coveralls
deploy:
  provider: pypi
  user: sunzhongmou
  password:
    secure: oDuJdyMaYZfqeAnJAsznEc9BQEhtFD5XjLNhn7lVTAjMwoP/Uo9IBDe0of0meqdMXbVegky6xjnLQDV7cLRFxVMHO7wkfqpCCpC8AsBwbtIguiKjsaLN4w1mQOLtw9qHaExqcx/2zBoGx+Kssl4nmi0nxU4jEcjAMmtwp5IACWf2ClNrCsqTurDbbviruCxRZknsCrEe2pwXDOlcOP4GUlV7L/yopWyDvrFqRkXUlkJ2Zz+CQt7V8beWTmRqesEyJ/HPWmjIpmvdOSQLR/lbyzt9GLVhCCqxL11iJs8Boh+63FOCQhG63ZfQ8+gEovXHxPkowuey0e4HICwxVq0RkDB20jqdU9fzjlsSQbakFZUSdoCvhCnubApg0+gd4zHYzvW/+CYfhpSfDwcvmk9DESX0+sq7VxQFm65FwXi7qwhUDo0AaUVJtntVzvyJLo2Ltyu1pDnEjXxX7K0JOicI5xj58rQ13mOomYbQJ7x8kDcCzfwj/qmpCU5j0PZoyLhzsv1tqwjeaaPbpbKoXbofi9DYkdwl5H2YefYcWUDbZBvHHLQzSITL4+71n6RHH0ud6/PpHj3mVXQoGO157BAQVjey+gUfb8La2yhPILXixQst0pa6fl/MZ83534FO5KJ/+bBAUdHOjHARjI0+N22l8cUJae7J0j2C9rTNIycgbHU=
  on:
    python: 2.7
